language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons: 
  sonarcloud:
      organization: "gorob-github"
      token:
        secure: svTuffwiGFHLZn+6bEtHDErCU2BwVw7ERmvvcmrD/1EATmg9+2HuA/Qq/9dYnYXhMxrYB7PcT45zkrwjXwpek8npaPzSIU6noN3Y/qWhvMJ4bB22LD56W37lJ+NUW+HP7nJF86/+pPIEWZszJ6dW/b1TFljl+yBjnwnOnS2k+5ypjNp7uBizV4uhb/KiHu2IHnk962J5N72AsgSCqg4l4dFXA0M7aroT+ACJGt08Vy+rUT5+ifR3MntphG/+8OLQLxJ/c4z6qG2f3bf+3du8UeVyg4YATnc2rz+5HuOe2bT4T7Hp8r1f5/EYYNBV6Je7VHmJgpsRwdAOShpi4LX+KW0EO/YfvV6uXVF5aKGJvMAeQIqyXLsgOMcJj+rbREiSMcEw4Rka3H/S8GvBaYKW6qXUy7R3fTiiXxgoN9/rZlqMCGJ9wt0GBaQuJG2ISYoi4yao38iDi+S+lh1K+m+BtXUkvAB5aafiZLlvRtFMCp4EwolnV289QgJ8ZwEsJ2W2Jx7tVDlZgkgkEK3jOFW2wy68j89WyatWaEIHIyi4o/T6+uU6mkamns4MPQ5c+75YZ79nk/MkXDd49gEMIzQFJrZtk6Qj+cxXNocVU3ckZIU5ktt9GH2+ZftJ0CRbuGznLHEOFw/ycy/4R3M5TrnAPOjH9NQjh2sknk9NbQhlwuI=
      
      branches:
        - master

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
 
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false    
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_script: 
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start" 
  - "sleep 3" 
  