language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons: 
  sonarcloud:
      organization: "gorob-github"
      token:
        secure: MtL3cWt7by0AM1oWh60db7Lo3TImix08KhW2z/udB9xoh8sPW2Qj/mXomRGzr78UxiAY6AnWofrXi1r3WCSxm1JsuXqh8w+Isu4fICbw+jzgNZRVdpd/aq2vFmeYkeLmmll+8MdRUpQELmhnMIfcEuruXPOxa7dOc2lDJN/vGnDB3jQAhX+7/EmGT2XP+uvN95ipxZgBaIKK8WtJSjkuRIicE7u4g3MA5QEscD849jIwiJpe92exPepRjcbfth0d6IM+xzQMF1jWzVauX8+dI5ykV6P1xXjgdNU82SZBkjo757TrDux+Y2JGt80TjMLI/Rl0CKLDbumNwYUNcbS7D/suzGi07wUeF55N0fYh5OPeg2/Vuh1Uj/MX+KdoRHbTN9wKHQpdr9CVe16N0Au8l3yT1UUl/M2apovMEJynnxMnNe4epHm1nWieTpRDi/i1Whl/UOJx/uaIpHqmwfjmJDyBv1n5szwNPhlqdde1AedvHwV8IezbzwASjtD04ckd5YfIYS8XCphKwOBr+jlj36To5LeluBU4ECSzQtz259DRLzImRWxxrqfvVM9tJURBqM6XGL8vTxjpKBK45oNo8lDJ9tD3l6py5ZFm7WDtSHLq28D+zCUxKjwPPV9EPBC8gfvma1KOBBK07oEh3IUbznR8IWTMf7seRDe29lUQhAo=
      
      branches:
        - master

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
 
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false    
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_script: 
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start" 
  - "sleep 3" 
  