language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons: 
  sonarcloud:
      organization: "gorob-github"
      token:
        secure: KcI4o4SUBNQDxTp5+zRNDpeiKrJhjmKJGvMsAbynMq3rHcO53iqYn4Mxgq0yV9x1YuRiUD4hFV8bIcpXL+Ril+aLKLsd0O6FjXhqe6InIFtZiGY2SFU2LttCG3laY3QTUQ1ARbwf9qMZf3zwGg2aQheWcZp58yQ0rWVayk3Cfx8AjmLWZO6OITMMtE27F+WUyY8Bgd9SDbL6haX0XV0jVJQ0mralmkl+xGRxiv0ZNVlPKJDATUW1Jx3W+oXIiQ5+1Ob2vQEJEV8wTMNIjpAmQGN/lPambfFRx7px9DG4s8+fQmBOUEnQ07RJEWZy8VV+2xEJ/EML2TDD8kMiSsksqYWUZqoL7GF2L4tQYuaoXRoiegLQOtY0ke5a1OHifpj5iwKxydmZ+eT0nyEICToDn3dUTo25Rf+b8axlXKOjyOPNez+G2EKCxtMtAmlVtHcDViPfrDpY4FaDNqh4hIt86w2+IyCMPrB688YdX+qGKCxEALOfcPyyVRkZsqBERmCaJmfC2oYEnwvEL0c1qfwOLWbg7pYha8JiSqAdgK0HR0bkmvRBk5sIiE+RAyDvsYmFWe/6tajc64UxfYWgzJINaJ3K5YGPXYleq3vOlZ3PruuU0b9Wr0X0wpn+IDcSpaE6eZx/9TUXQzJiajswYvsuqgZOdUf+Bp96Tif+S3mDuBA=
      
      branches:
        - master

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
 
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false    
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_script: 
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start" 
  - "sleep 3" 
  