language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons: 
  sonarcloud:
      organization: "uniqueck-github"
      token:
        secure: S5WdBY2dmKD9+Rqx+31SxT+lJkiQ74mEsU3rE/T0qgU1ffWKm2NsqHygCQ3jrt39Y6N3tlkGBjVirqVITcLSVWVUh+BtTZL2nCed+eJzkoP5b/XgMiJ/fOi4gU7y11BNTHse6lED05RIM4nW736pgiW4PJzP8fNqJEC2f6M4u2BvqTpXka7ZBoBnsuOfiHaBchKT/rjOqLag3wCrDWM5mxAE3lEBqT9l/whjiwsqw2A12bNm3Wsqz+dqaF5bGyirAncL003R4ayoqzH7LogkvvlPv3wr8IpB9IJhInrL1htbJPGTix4aMQTyhmp+Ij22V9OQB4CuFwSQRReO1Mm4kGVwlEfsLq78pLqDYJCuvqbyy+JgoFm4xuyKBQdoxBCx40zTJGHm8xi8wWC1MSZJIgzeMYVT2Zx4eBnV/5N8dEozDrViRdan0MX38smyvd/WCn5OnASbcyVFynuugREGiLbQHGn4DmWwl1JKGgh2ZzY9H7eV5d5+RJeB8nfzh3xk1MtnO3Ii5RPInasOOQg496fJ2CNaxMyPP1oRocoP5nzlAEROwD8BqCeikmlQOXAUVTCvcu1J5EeRQEoba+SH3reJqAM2tMryYt6hGG9mSNoldvJS8H2tAwX9tZiRNsGCvR9JuKYkm9uIllO8/jnlFlCQ6ZkP9sCLvTdCqLRIQfg=
      branches:
        - master

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
 
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false    
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
